version: "3"
services:
  freqtrade:
    image: docker.io/library/freqtrade-proxychains:2025.1
    restart: unless-stopped
    container_name: freqtrade
    environment:
      PROXY_TYPE: http
      PROXY_HOST: 192.168.123.52
      PROXY_PORT: 8889
    volumes:
      - ./user_data:/freqtrade/user_data
    ports:
      - 8080:8080
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy